In [28]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [29]:
df1 = pd.read_csv('E:/Downloads/raw.githubusercontent.com_alexeygrigorev_mlbookcamp-code_master_chapter-02-car-price_data.csv')

In [30]:
df1.head()

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

In [31]:
df1.dtypes

Make                  object
Model                 object
Year                   int64
Engine Fuel Type      object
Engine HP            float64
Engine Cylinders     float64
Transmission Type     object
Driven_Wheels         object
Number of Doors      float64
Market Category       object
Vehicle Size          object
Vehicle Style         object
highway MPG            int64
city mpg               int64
Popularity             int64
MSRP                   int64
dtype: object

In [32]:
df1.drop(columns=['Engine Fuel Type', 'Driven_Wheels', 'Number of Doors', 'Market Category', 'Vehicle Size', 'Popularity'], inplace=True)

In [33]:
df1.head()

Make       Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0  BMW  1 Series M  2011      335.0               6.0            MANUAL   
1  BMW    1 Series  2011      300.0               6.0            MANUAL   
2  BMW    1 Series  2011      300.0               6.0            MANUAL   
3  BMW    1 Series  2011      230.0               6.0            MANUAL   
4  BMW    1 Series  2011      230.0               6.0            MANUAL   

  Vehicle Style  highway MPG  city mpg   MSRP  
0         Coupe           26        19  46135  
1   Convertible           28        19  40650  
2         Coupe           28        20  36350  
3         Coupe           28        18  29450  
4   Convertible           28        18  34500

In [34]:
df1.columns = df1.columns.str.replace(' ', '_').str.lower()

In [35]:
df1 = df1.fillna(0)

In [36]:
df1.isnull().sum()

make                 0
model                0
year                 0
engine_hp            0
engine_cylinders     0
transmission_type    0
vehicle_style        0
highway_mpg          0
city_mpg             0
msrp                 0
dtype: int64

In [37]:
df1.rename(columns= {'msrp': 'price'}, inplace=True)

In [38]:
df1.head()

make       model  year  engine_hp  engine_cylinders transmission_type  \
0  BMW  1 Series M  2011      335.0               6.0            MANUAL   
1  BMW    1 Series  2011      300.0               6.0            MANUAL   
2  BMW    1 Series  2011      300.0               6.0            MANUAL   
3  BMW    1 Series  2011      230.0               6.0            MANUAL   
4  BMW    1 Series  2011      230.0               6.0            MANUAL   

  vehicle_style  highway_mpg  city_mpg  price  
0         Coupe           26        19  46135  
1   Convertible           28        19  40650  
2         Coupe           28        20  36350  
3         Coupe           28        18  29450  
4   Convertible           28        18  34500

In [39]:
for col in df1.columns:
    print(col)
    print(df1[col].unique()[:5])
    print(df1[col].nunique())
    print()

make
['BMW' 'Audi' 'FIAT' 'Mercedes-Benz' 'Chrysler']
48

model
['1 Series M' '1 Series' '100' '124 Spider' '190-Class']
915

year
[2011 2012 2013 1992 1993]
28

engine_hp
[335. 300. 230. 320. 172.]
357

engine_cylinders
[ 6.  4.  5.  8. 12.]
9

transmission_type
['MANUAL' 'AUTOMATIC' 'AUTOMATED_MANUAL' 'DIRECT_DRIVE' 'UNKNOWN']
5

vehicle_style
['Coupe' 'Convertible' 'Sedan' 'Wagon' '4dr Hatchback']
16

highway_mpg
[26 28 27 25 24]
59

city_mpg
[19 20 18 17 16]
69

price
[46135 40650 36350 29450 34500]
6049



### Question 1

In [40]:
df1['transmission_type'].value_counts()

AUTOMATIC           8266
MANUAL              2935
AUTOMATED_MANUAL     626
DIRECT_DRIVE          68
UNKNOWN               19
Name: transmission_type, dtype: int64

AUTOMATIC is the most frequent observation for the column transmission_type

### Question 2

In [41]:
df1.dtypes

make                  object
model                 object
year                   int64
engine_hp            float64
engine_cylinders     float64
transmission_type     object
vehicle_style         object
highway_mpg            int64
city_mpg               int64
price                  int64
dtype: object

In [42]:
numerical = ['year', 'engine_hp', 'engine_cylinders', 'highway_mpg', 'city_mpg']

In [43]:
df1.corr(numeric_only=True)

year  engine_hp  engine_cylinders  highway_mpg  \
year              1.000000   0.338714         -0.040708     0.258240   
engine_hp         0.338714   1.000000          0.774851    -0.415707   
engine_cylinders -0.040708   0.774851          1.000000    -0.614541   
highway_mpg       0.258240  -0.415707         -0.614541     1.000000   
city_mpg          0.198171  -0.424918         -0.587306     0.886829   
price             0.227590   0.650095          0.526274    -0.160043   

                  city_mpg     price  
year              0.198171  0.227590  
engine_hp        -0.424918  0.650095  
engine_cylinders -0.587306  0.526274  
highway_mpg       0.886829 -0.160043  
city_mpg          1.000000 -0.157676  
price            -0.157676  1.000000

engine_hp and engine_cylinders have the biggest correlation in this dataset

In [44]:
df1['above_average'] = (df1['price'] > df1['price'].mean()).astype(int)

In [45]:
df = df1.copy()

In [46]:
df = df.drop(columns='price')

In [47]:
df.head()

make       model  year  engine_hp  engine_cylinders transmission_type  \
0  BMW  1 Series M  2011      335.0               6.0            MANUAL   
1  BMW    1 Series  2011      300.0               6.0            MANUAL   
2  BMW    1 Series  2011      300.0               6.0            MANUAL   
3  BMW    1 Series  2011      230.0               6.0            MANUAL   
4  BMW    1 Series  2011      230.0               6.0            MANUAL   

  vehicle_style  highway_mpg  city_mpg  above_average  
0         Coupe           26        19              1  
1   Convertible           28        19              1  
2         Coupe           28        20              0  
3         Coupe           28        18              0  
4   Convertible           28        18              0

In [48]:
from sklearn.model_selection import train_test_split

In [49]:
df_full_train, df_test = train_test_split(df, test_size=0.2, random_state=42)

In [50]:
df_train, df_val = train_test_split(df_full_train, test_size=0.25, random_state=42)

In [51]:
len(df_train), len(df_val), len(df_test)

(7148, 2383, 2383)

In [52]:
df_train = df_train.reset_index(drop=True)
df_val = df_val.reset_index(drop=True)
df_test = df_test.reset_index(drop=True)

In [53]:
y_train = df_train.above_average.values
y_val = df_val.above_average.values
y_test = df_test.above_average.values

In [54]:
del df_train['above_average']
del df_val['above_average']
del df_test['above_average']

In [55]:
df_train.head()

make     model  year  engine_hp  engine_cylinders transmission_type  \
0   Mitsubishi  Endeavor  2011      225.0               6.0         AUTOMATIC   
1          Kia   Borrego  2009      276.0               6.0         AUTOMATIC   
2  Lamborghini  Gallardo  2012      570.0              10.0            MANUAL   
3    Chevrolet  Colorado  2016      200.0               4.0         AUTOMATIC   
4      Pontiac      Vibe  2009      158.0               4.0         AUTOMATIC   

     vehicle_style  highway_mpg  city_mpg  
0          4dr SUV           19        15  
1          4dr SUV           21        17  
2      Convertible           20        12  
3  Crew Cab Pickup           27        20  
4    4dr Hatchback           26        20

### Question 3

In [56]:
df_full_train = df_full_train.reset_index(drop=True)

In [57]:
df_full_train.head()

make      model  year  engine_hp  engine_cylinders  \
0       Cadillac        CT6  2016      265.0               4.0   
1  Mercedes-Benz  GLS-Class  2017      449.0               8.0   
2            Kia      Forte  2016      173.0               4.0   
3          Dodge    RAM 250  1993      180.0               6.0   
4        Hyundai    Tiburon  2008      172.0               6.0   

  transmission_type       vehicle_style  highway_mpg  city_mpg  above_average  
0         AUTOMATIC               Sedan           31        22              1  
1         AUTOMATIC             4dr SUV           18        14              1  
2         AUTOMATIC               Coupe           34        25              0  
3            MANUAL  Regular Cab Pickup           16        11              0  
4         AUTOMATIC       2dr Hatchback           24        17              0

In [58]:
categorical = ['make', 'model', 'transmission_type', 'vehicle_style']

In [59]:
from sklearn.metrics import mutual_info_score

In [60]:
def mutual_info_above_average_score(series):
    return mutual_info_score(series, df_full_train.above_average)

In [61]:
mi = df_full_train[categorical].apply(mutual_info_above_average_score)
mi.sort_values(ascending=False)

model                0.460994
make                 0.238724
vehicle_style        0.083390
transmission_type    0.020884
dtype: float64

transmission_type has the lowest mutual information score

### Question 4

In [62]:
from sklearn.feature_extraction import DictVectorizer

In [63]:
train_dicts = df_train[categorical + numerical].to_dict(orient='records')

In [64]:
train_dicts[0]

{'make': 'Mitsubishi',
 'model': 'Endeavor',
 'transmission_type': 'AUTOMATIC',
 'vehicle_style': '4dr SUV',
 'year': 2011,
 'engine_hp': 225.0,
 'engine_cylinders': 6.0,
 'highway_mpg': 19,
 'city_mpg': 15}

In [65]:
dv = DictVectorizer(sparse=False)

In [66]:
X_train = dv.fit_transform(train_dicts)

In [67]:
val_dicts = df_val[categorical + numerical].to_dict(orient='records')

In [68]:
X_val = dv.transform(val_dicts)

In [69]:
from sklearn.linear_model import LogisticRegression

In [70]:
model = LogisticRegression(solver='liblinear', C=10, max_iter=1000, random_state=42)

In [71]:
model.fit(X_train, y_train)

LogisticRegression(C=10, max_iter=1000, random_state=42, solver='liblinear')

In [72]:
y_pred = model.predict_proba(X_val)[:, 1]

In [73]:
above_average_decision = (y_pred >= 0.5)

In [74]:
(y_val == above_average_decision).mean().round(2)

0.95

The accuracy of the model on the validation dataset is 0.95

### Question 5

In [75]:
original_accuracy = 0.95
total_categories = []
total_categories = numerical + categorical
for i in total_categories:
    print(i)
    total_categories.remove(i)
    train_dicts = df_train[total_categories].to_dict(orient='records')
    X_train = dv.fit_transform(train_dicts)
    val_dicts = df_val[total_categories].to_dict(orient='records')
    X_val = dv.transform(val_dicts)
    model.fit(X_train, y_train)
    y_pred = model.predict_proba(X_val)[:, 1]
    above_average_decision = (y_pred >= 0.5)
    difference = original_accuracy - (y_val == above_average_decision).mean()
    print(difference)
    total_categories = numerical + categorical

year
0.0020352496852705793
engine_cylinders
0.0028745279060008455
highway_mpg
0.005812001678556444
city_mpg
0.004133445237096023
make
0.0007763323541754019
model
0.025954678976080503
transmission_type
0.004972723457826178
vehicle_style
0.007490558120016755


In [76]:
total_categories = numerical + categorical

In [77]:
print(total_categories[1])
total_categories.remove(total_categories[1])
train_dicts = df_train[total_categories].to_dict(orient='records')
X_train = dv.fit_transform(train_dicts)
val_dicts = df_val[total_categories].to_dict(orient='records')
X_val = dv.transform(val_dicts)
model.fit(X_train, y_train)
y_pred = model.predict_proba(X_val)[:, 1]
above_average_decision = (y_pred >= 0.5)
difference = original_accuracy - (y_val == above_average_decision).mean()
print(difference)

engine_hp
0.019660092320604283


Out of all the given options, year has the smallest difference between the original accuracy and the accuracy without the feature.

### Question 6

In [78]:
df1.drop(columns='above_average', inplace=True)

In [79]:
df1.head()

make       model  year  engine_hp  engine_cylinders transmission_type  \
0  BMW  1 Series M  2011      335.0               6.0            MANUAL   
1  BMW    1 Series  2011      300.0               6.0            MANUAL   
2  BMW    1 Series  2011      300.0               6.0            MANUAL   
3  BMW    1 Series  2011      230.0               6.0            MANUAL   
4  BMW    1 Series  2011      230.0               6.0            MANUAL   

  vehicle_style  highway_mpg  city_mpg  price  
0         Coupe           26        19  46135  
1   Convertible           28        19  40650  
2         Coupe           28        20  36350  
3         Coupe           28        18  29450  
4   Convertible           28        18  34500

In [80]:
df1['price'] = np.log1p(df1.price.values)

In [81]:
df1.head()

make       model  year  engine_hp  engine_cylinders transmission_type  \
0  BMW  1 Series M  2011      335.0               6.0            MANUAL   
1  BMW    1 Series  2011      300.0               6.0            MANUAL   
2  BMW    1 Series  2011      300.0               6.0            MANUAL   
3  BMW    1 Series  2011      230.0               6.0            MANUAL   
4  BMW    1 Series  2011      230.0               6.0            MANUAL   

  vehicle_style  highway_mpg  city_mpg      price  
0         Coupe           26        19  10.739349  
1   Convertible           28        19  10.612779  
2         Coupe           28        20  10.500977  
3         Coupe           28        18  10.290483  
4   Convertible           28        18  10.448744

In [82]:
from sklearn.model_selection import train_test_split
df1_full_train, df1_test = train_test_split(df1, test_size=0.2, random_state=42)
df1_train, df1_val = train_test_split(df1_full_train, test_size=0.25, random_state=42)
len(df1_train), len(df1_val), len(df1_test)

(7148, 2383, 2383)

In [83]:
df1_train = df1_train.reset_index(drop=True)
df1_val = df1_val.reset_index(drop=True)
df1_test = df1_test.reset_index(drop=True)

In [84]:
y_train = df1_train.price.values
y_val = df1_val.price.values
y_test = df1_test.price.values

In [85]:
del df1_train['price']
del df1_val['price']
del df1_test['price']

In [86]:
from sklearn.linear_model import Ridge

In [87]:
categorical = ['make', 'model', 'transmission_type', 'vehicle_style']
numerical = ['year', 'engine_hp', 'engine_cylinders', 'highway_mpg', 'city_mpg']

In [90]:
from sklearn.feature_extraction import DictVectorizer
train_dicts = df1_train[categorical + numerical].to_dict(orient='records')
dv = DictVectorizer(sparse=False)
X_train = dv.fit_transform(train_dicts)
val_dicts = df1_val[categorical + numerical].to_dict(orient='records')
X_val = dv.transform(val_dicts)

In [92]:
def rmse(y, y_pred):
    error = y - y_pred
    se = error**2
    mse = se.mean()
    return np.sqrt(mse)

In [93]:
alpha_values = [0, 0.01, 0.1, 1, 10]
rmse_scores = {}
for alpha in alpha_values:
    ridge_model = Ridge(alpha=alpha, solver='sag', random_state=42)
    ridge_model.fit(X_train, y_train)
    y_pred = ridge_model.predict(X_val)
    rmse = rmse(y_pred, y_train)
    rmse_scores[alpha] = round(rmse, 3)
for alpha, rmse in rmse_scores.items():
    print(f"Alpha={alpha}: RMSE={rmse}")

KeyboardInterrupt: 